#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo "\n🧪 Running unit tests...\n"
npm run test:ci

echo "\n🧱 Building project for end-to-end testing...\n"
npm run build

echo "\n🚀 Running end-to-end tests...\n"
npm run e2e
