#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo "🧪 Running unit tests..."
npm run test:ci

echo "🧱 Building project for end-to-end testing..."
npm run build

echo "🚀 Running end-to-end tests..."
npm run e2e
