# This workflow will run all tests suites and build the project.
# It will be used to test the project before pushing it to the repository.
name: Test and Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        # uses: actions/setup-node@v2
        run: npm install
        with:
          node-version: ${{ matrix.node-version }}
      - name: Run unit tests
        run: npm test
      - name: Run end-to-end tests
        run: npm run e2e
